// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNoQ0IBogFnGZwkTBdrPZUnYp6bKUUi8',
    appId: '1:486675566399:web:392ac5faa2d37b91d44d8a',
    messagingSenderId: '486675566399',
    projectId: 'denv-funcs',
    authDomain: 'denv-funcs.firebaseapp.com',
    storageBucket: 'denv-funcs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVki1XBfHWUzS3iEHw7fKtV9_Ey85dhL4',
    appId: '1:486675566399:android:3fc30c73c7b73adbd44d8a',
    messagingSenderId: '486675566399',
    projectId: 'denv-funcs',
    storageBucket: 'denv-funcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvwhH1bDl5Jt8eCp0Ljzo4O9bKJgrNsbM',
    appId: '1:486675566399:ios:63f4b56217aa907fd44d8a',
    messagingSenderId: '486675566399',
    projectId: 'denv-funcs',
    storageBucket: 'denv-funcs.appspot.com',
    iosClientId: '486675566399-5a6rqdm3mt238b71a54fg6uknvl67od5.apps.googleusercontent.com',
    iosBundleId: 'com.example.denvFlutterTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvwhH1bDl5Jt8eCp0Ljzo4O9bKJgrNsbM',
    appId: '1:486675566399:ios:75d4486bebace904d44d8a',
    messagingSenderId: '486675566399',
    projectId: 'denv-funcs',
    storageBucket: 'denv-funcs.appspot.com',
    iosClientId: '486675566399-l8rd7c6nsp83514sh91fnuqktr473586.apps.googleusercontent.com',
    iosBundleId: 'com.example.denvFlutterTraining.RunnerTests',
  );
}
